In [87]:
!pip install transformers datasets

In [88]:
!pip install conllu

In [89]:
from datasets import load_dataset, get_dataset_config_names

In [90]:
name = "universal_dependencies"

In [91]:
ud_config = get_dataset_config_names(name)

In [92]:
ud_config

['af_afribooms',
 'akk_pisandub',
 'akk_riao',
 'aqz_tudet',
 'sq_tsa',
 'am_att',
 'grc_perseus',
 'grc_proiel',
 'apu_ufpa',
 'ar_nyuad',
 'ar_padt',
 'ar_pud',
 'hy_armtdp',
 'aii_as',
 'bm_crb',
 'eu_bdt',
 'be_hse',
 'bho_bhtb',
 'br_keb',
 'bg_btb',
 'bxr_bdt',
 'yue_hk',
 'ca_ancora',
 'zh_cfl',
 'zh_gsd',
 'zh_gsdsimp',
 'zh_hk',
 'zh_pud',
 'ckt_hse',
 'lzh_kyoto',
 'cop_scriptorium',
 'hr_set',
 'cs_cac',
 'cs_cltt',
 'cs_fictree',
 'cs_pdt',
 'cs_pud',
 'da_ddt',
 'nl_alpino',
 'nl_lassysmall',
 'en_esl',
 'en_ewt',
 'en_gum',
 'en_gumreddit',
 'en_lines',
 'en_partut',
 'en_pronouns',
 'en_pud',
 'myv_jr',
 'et_edt',
 'et_ewt',
 'fo_farpahc',
 'fo_oft',
 'fi_ftb',
 'fi_ood',
 'fi_pud',
 'fi_tdt',
 'fr_fqb',
 'fr_ftb',
 'fr_gsd',
 'fr_partut',
 'fr_pud',
 'fr_sequoia',
 'fr_spoken',
 'gl_ctg',
 'gl_treegal',
 'de_gsd',
 'de_hdt',
 'de_lit',
 'de_pud',
 'got_proiel',
 'el_gdt',
 'he_htb',
 'qhe_hiencs',
 'hi_hdtb',
 'hi_pud',
 'hu_szeged',
 'is_icepahc',
 'is_pud',
 'id_csui'

In [93]:
print([x for x in ud_config if 'en_' in x])

['en_esl', 'en_ewt', 'en_gum', 'en_gumreddit', 'en_lines', 'en_partut', 'en_pronouns', 'en_pud']


In [94]:
ud_ewt_train = load_dataset(name, 'en_ewt', split="train")

In [95]:
ud_ewt_train

Dataset({
    features: ['idx', 'text', 'tokens', 'lemmas', 'upos', 'xpos', 'feats', 'head', 'deprel', 'deps', 'misc'],
    num_rows: 12543
})

In [96]:
ud_ewt_train[0]['tokens']

['Al',
 '-',
 'Zaman',
 ':',
 'American',
 'forces',
 'killed',
 'Shaikh',
 'Abdullah',
 'al',
 '-',
 'Ani',
 ',',
 'the',
 'preacher',
 'at',
 'the',
 'mosque',
 'in',
 'the',
 'town',
 'of',
 'Qaim',
 ',',
 'near',
 'the',
 'Syrian',
 'border',
 '.']

2.a Verification of 1st sentence which has 29 tokens

In [97]:
len(ud_ewt_train[0]['tokens'])

29

2.a Number of sentences in training splits

In [98]:
len(ud_ewt_train)

12543

In [99]:
ud_ewt_validation = load_dataset(name, 'en_ewt', split="validation")

In [100]:
ud_ewt_validation

Dataset({
    features: ['idx', 'text', 'tokens', 'lemmas', 'upos', 'xpos', 'feats', 'head', 'deprel', 'deps', 'misc'],
    num_rows: 2002
})

2.a Number of sentences in validation splits

In [101]:
len(ud_ewt_validation)

2002

2.a Average words per sentence for train split sentences

In [102]:
count_train=len(ud_ewt_train)
temp_sum=0
temp_sum_type=set()
for i in range(count_train):
  temp_sum = temp_sum + len(ud_ewt_train[i]['tokens'])
  #temp_sum_type = temp_sum_type + len(list(set(ud_ewt_train[i]['tokens'])))
  temp_sum_type.update(ud_ewt_train[i]['tokens'])
avg_word_per_sentence = temp_sum/count_train
print(avg_word_per_sentence)
print(temp_sum_type)

16.50745435701188
{'sponsorship', '1.8', 'co-operate', 'Rise', 'harmony', 'non-compete', 'undergraduate', 'Grand', 'risks', 'STUFF', 'Handwritten', 'Warner', 'Senators', 'Syria', 'thinking', 'thing', 'Marquez', 'users', '...........', '5.1', 'over-simplifying', 'clearer', 'Suez', 'Soldiers', 'proficient', 'Lorenzo', 'mousey', 'Chumley', 'comic', 'gross', 'comments', 'concrete', 'selecting', 'Labadee', 'tankmates', 'Riding', 'http://www.UnitaryExecutive.net', 'Hearing', 'chimichangas', '10:16', 'jaws', 'Horrible', 'bolder', 'tupperwear', 'rosy', '11:16:58', 'horror', 'Coffman', '01/24/2001', 'Capricorn', 'St.', 'Hirsohima', 'your', 'limit', 'disregard', 'Provisions', 'acupuncturist', 'unwittingly', 'brumation', 'gaming', 'Iranians', 'Logan', 'Expressway', 'Naturalisation', 'drags', '14th', 'tendencies', 'wins', 'efficient', 'journalist', 'Juego', 'Revell', 'mullahs', "she'll", 'Structuring', 'preferable', 'Ukraine', 'dwellers', 'Aye', 'Nagin', '03:48', 'agencies', 'guest', 'Sandra', 'Br

2.a Average words per sentence for validation split sentences

In [103]:
count_validation=len(ud_ewt_validation)
temp_sum1=0
val_type=set()
for i in range(count_validation):
  temp_sum1 = temp_sum1 + len(ud_ewt_validation[i]['tokens'])
  val_type.update(ud_ewt_validation[i]['tokens'])
avg_word_per_sentence1 = temp_sum1/count_validation
print(avg_word_per_sentence1)

12.726273726273726


2.b Total number of Tokens and Total number of Types

In [104]:
print("Tokens train: ",temp_sum)
print("Type train: ", len(list(temp_sum_type)))

Tokens train:  207053
Type train:  20132


2.c

In [105]:
dic = {}
count_train=len(ud_ewt_train)
temp_sum=0
temp_sum_type=set()
for i in range(count_train):
  for j in range(len(ud_ewt_train[i]['tokens'])):
    if ud_ewt_train[i]['tokens'][j] in dic:
      dic[ud_ewt_train[i]['tokens'][j]] +=1
    else:
      dic[ud_ewt_train[i]['tokens'][j]] =1
  temp_sum = temp_sum + len(ud_ewt_train[i]['tokens'])
  #temp_sum_type = temp_sum_type + len(list(set(ud_ewt_train[i]['tokens'])))
  temp_sum_type.update(ud_ewt_train[i]['tokens'])
avg_word_per_sentence = temp_sum/count_train
#print(avg_word_per_sentence)
print(dic)


{'Al': 78, '-': 1426, 'Zaman': 3, ':': 593, 'American': 70, 'forces': 30, 'killed': 18, 'Shaikh': 4, 'Abdullah': 1, 'al': 36, 'Ani': 1, ',': 7021, 'the': 8152, 'preacher': 2, 'at': 745, 'mosque': 2, 'in': 2911, 'town': 43, 'of': 3589, 'Qaim': 2, 'near': 28, 'Syrian': 9, 'border': 13, '.': 8640, '[': 34, 'This': 210, 'killing': 12, 'a': 3609, 'respected': 1, 'cleric': 1, 'will': 816, 'be': 1116, 'causing': 5, 'us': 167, 'trouble': 14, 'for': 1789, 'years': 148, 'to': 5076, 'come': 101, ']': 34, 'DPA': 1, 'Iraqi': 39, 'authorities': 11, 'announced': 10, 'that': 1948, 'they': 832, 'had': 478, 'busted': 1, 'up': 393, '3': 125, 'terrorist': 19, 'cells': 5, 'operating': 15, 'Baghdad': 11, 'Two': 17, 'them': 347, 'were': 395, 'being': 144, 'run': 46, 'by': 599, '2': 159, 'officials': 30, 'Ministry': 3, 'Interior': 1, '!': 529, 'The': 885, 'MoI': 1, 'Iraq': 119, 'is': 2153, 'equivalent': 4, 'US': 162, 'FBI': 20, 'so': 440, 'this': 923, 'would': 578, 'like': 393, 'having': 67, 'J.': 3, 'Edgar':

In [106]:
print(dic['Twenty'])
print(temp_sum_type)
print(temp_sum)

1
{'sponsorship', '1.8', 'co-operate', 'Rise', 'harmony', 'non-compete', 'undergraduate', 'Grand', 'risks', 'STUFF', 'Handwritten', 'Warner', 'Senators', 'Syria', 'thinking', 'thing', 'Marquez', 'users', '...........', '5.1', 'over-simplifying', 'clearer', 'Suez', 'Soldiers', 'proficient', 'Lorenzo', 'mousey', 'Chumley', 'comic', 'gross', 'comments', 'concrete', 'selecting', 'Labadee', 'tankmates', 'Riding', 'http://www.UnitaryExecutive.net', 'Hearing', 'chimichangas', '10:16', 'jaws', 'Horrible', 'bolder', 'tupperwear', 'rosy', '11:16:58', 'horror', 'Coffman', '01/24/2001', 'Capricorn', 'St.', 'Hirsohima', 'your', 'limit', 'disregard', 'Provisions', 'acupuncturist', 'unwittingly', 'brumation', 'gaming', 'Iranians', 'Logan', 'Expressway', 'Naturalisation', 'drags', '14th', 'tendencies', 'wins', 'efficient', 'journalist', 'Juego', 'Revell', 'mullahs', "she'll", 'Structuring', 'preferable', 'Ukraine', 'dwellers', 'Aye', 'Nagin', '03:48', 'agencies', 'guest', 'Sandra', 'Brigades', 'Off', 

In [107]:
from operator import itemgetter
sorted_dic = dict(sorted(dic.items(), key=itemgetter(1), reverse=True))

In [108]:
sorted_dic

{'.': 8640,
 'the': 8152,
 ',': 7021,
 'to': 5076,
 'and': 4855,
 'a': 3609,
 'of': 3589,
 'I': 3122,
 'in': 2911,
 'is': 2153,
 'that': 1948,
 'you': 1920,
 'for': 1789,
 'it': 1472,
 '-': 1426,
 'have': 1320,
 '"': 1296,
 'was': 1230,
 'on': 1216,
 'with': 1175,
 'be': 1116,
 'are': 1083,
 'not': 954,
 'this': 923,
 "'s": 906,
 ')': 886,
 'The': 885,
 'as': 856,
 '(': 852,
 'they': 832,
 'will': 816,
 '?': 764,
 'my': 763,
 'at': 745,
 'do': 732,
 'or': 699,
 "n't": 645,
 'from': 637,
 'your': 632,
 'he': 630,
 'we': 615,
 'but': 615,
 'by': 599,
 ':': 593,
 'me': 588,
 'can': 583,
 'would': 578,
 '!': 529,
 'has': 509,
 'had': 478,
 'an': 476,
 'all': 471,
 'if': 453,
 'out': 443,
 'about': 442,
 'so': 440,
 'there': 438,
 'one': 437,
 'were': 395,
 'up': 393,
 'like': 393,
 'their': 391,
 'time': 385,
 'get': 378,
 'his': 364,
 'just': 353,
 'It': 348,
 'them': 347,
 'been': 340,
 'know': 339,
 'who': 336,
 'which': 334,
 'what': 329,
 'some': 327,
 'our': 321,
 'when': 307,
 'very

2.e

In [109]:
least_occurred=dict(sorted(dic.items(), key=itemgetter(1)))
least_occurred

{'Abdullah': 1,
 'Ani': 1,
 'respected': 1,
 'cleric': 1,
 'DPA': 1,
 'busted': 1,
 'Interior': 1,
 'MoI': 1,
 'Edgar': 1,
 'Hoover': 1,
 'unwittingly': 1,
 'Weathermen': 1,
 'manipulating': 1,
 'Ghazaliyah': 1,
 'districts': 1,
 'penetrate': 1,
 'reminds': 1,
 'Kurdistan': 1,
 'kidnapping': 1,
 'Ninevah': 1,
 'whereas': 1,
 'kidnappings': 1,
 'kidnapped': 1,
 'cosmetic': 1,
 'Suwayrah': 1,
 'detonated': 1,
 'southeastern': 1,
 'saboteurs': 1,
 'Talal': 1,
 'Husain': 1,
 'dean': 1,
 'Mustansiriyah': 1,
 'Salikh': 1,
 'Asi': 1,
 "'Akkab": 1,
 'Jubur': 1,
 'garrison': 1,
 'protesting': 1,
 'Sarhid': 1,
 'gunmen': 1,
 'punishing': 1,
 'denied': 1,
 'exclude': 1,
 'excluded': 1,
 'Ahmad': 1,
 'marginalized': 1,
 'clientelage': 1,
 'recalled': 1,
 'blocked': 1,
 'punish': 1,
 'prosecute': 1,
 'Sharq': 1,
 'Awsat': 1,
 'eyewitness': 1,
 'massacre': 1,
 'Dujail': 1,
 'Adhamiya': 1,
 'Baghdadis': 1,
 'neighbourhoods': 1,
 'curfew': 1,
 'non-stop': 1,
 'bolder': 1,
 'indiscriminately': 1,
 "47'

In [110]:
dic_1 = {}

for key, value in least_occurred.items():
    if value == 1:
        dic_1[key] = value

print(dic_1)

{'Abdullah': 1, 'Ani': 1, 'respected': 1, 'cleric': 1, 'DPA': 1, 'busted': 1, 'Interior': 1, 'MoI': 1, 'Edgar': 1, 'Hoover': 1, 'unwittingly': 1, 'Weathermen': 1, 'manipulating': 1, 'Ghazaliyah': 1, 'districts': 1, 'penetrate': 1, 'reminds': 1, 'Kurdistan': 1, 'kidnapping': 1, 'Ninevah': 1, 'whereas': 1, 'kidnappings': 1, 'kidnapped': 1, 'cosmetic': 1, 'Suwayrah': 1, 'detonated': 1, 'southeastern': 1, 'saboteurs': 1, 'Talal': 1, 'Husain': 1, 'dean': 1, 'Mustansiriyah': 1, 'Salikh': 1, 'Asi': 1, "'Akkab": 1, 'Jubur': 1, 'garrison': 1, 'protesting': 1, 'Sarhid': 1, 'gunmen': 1, 'punishing': 1, 'denied': 1, 'exclude': 1, 'excluded': 1, 'Ahmad': 1, 'marginalized': 1, 'clientelage': 1, 'recalled': 1, 'blocked': 1, 'punish': 1, 'prosecute': 1, 'Sharq': 1, 'Awsat': 1, 'eyewitness': 1, 'massacre': 1, 'Dujail': 1, 'Adhamiya': 1, 'Baghdadis': 1, 'neighbourhoods': 1, 'curfew': 1, 'non-stop': 1, 'bolder': 1, 'indiscriminately': 1, "47's": 1, 'dream': 1, 'valiant': 1, 'rumours': 1, 'slum': 1, 'dwel

In [111]:
dic_10 = {}

for key, value in least_occurred.items():
    if value == 10:
        dic_10[key] = value

print(dic_10)

{'announced': 10, 'investment': 10, 'targets': 10, 'percent': 10, 'jump': 10, 'mother': 10, 'crime': 10, 'Iraqis': 10, 'stuck': 10, 'Everyone': 10, 'false': 10, '500': 10, 'radiation': 10, 'Union': 10, 'otherwise': 10, 'published': 10, 'links': 10, 'Khalid': 10, 'Make': 10, 'hate': 10, 'British': 10, 'shot': 10, 'appears': 10, 'candidate': 10, "world's": 10, 'potential': 10, 'conditions': 10, 'suffer': 10, 'closely': 10, 'reportedly': 10, 'launch': 10, 'chemical': 10, 'failed': 10, "Iran's": 10, 'authority': 10, 'private': 10, 'aid': 10, 'spread': 10, 'Middle': 10, 'decades': 10, 'sides': 10, 'closed': 10, 'de': 10, 'puts': 10, 'series': 10, 'forced': 10, 'degree': 10, 'sake': 10, 'remains': 10, 'corner': 10, 'F': 10, 'Before': 10, 'n’t': 10, 'hundreds': 10, 'earned': 10, '1972': 10, 'William': 10, 'Business': 10, 'notch': 10, 'perfectly': 10, 'entirely': 10, 'familiar': 10, 'promised': 10, 'floor': 10, 'barely': 10, 'vote': 10, 'reconciliation': 10, 'recall': 10, 'Judge': 10, 'wrote':

In [112]:
dic_100 = {}

for key, value in least_occurred.items():
    if value == 110:
        dic_100[key] = value

print(dic_100)

{'little': 110, 'long': 110}


In [113]:
dic_73 = {}

for key, value in least_occurred.items():
    if value >73:
        dic_73[key] = value

print(dic_73)

{'each': 74, 'getting': 74, 'She': 74, 'company': 74, 'office': 75, 'away': 75, 'try': 75, 'staff': 75, 'against': 76, "I've": 76, 'job': 76, 'room': 76, 'Number': 76, 'might': 77, 'found': 77, 'came': 77, 'New': 77, "It's": 77, 'Al': 78, 'under': 78, 'life': 78, 'old': 79, 'ever': 79, 'thing': 79, 'That': 79, 'went': 79, 'China': 79, 'anyone': 80, 'United': 81, 'night': 81, 'things': 81, 'recommend': 81, 'AM': 81, 'end': 82, 'looking': 82, 'doing': 83, 'keep': 83, 'Iran': 83, 'experience': 84, 'When': 84, 'change': 85, '10': 85, 'already': 86, 'family': 86, 'lot': 87, 'done': 87, 'money': 87, 'every': 88, 'something': 89, 'took': 89, 'home': 90, 'week': 90, 'while': 91, 'between': 91, 'business': 91, 'such': 92, 'So': 92, 'own': 92, 'name': 92, 'look': 92, 'feel': 94, 'As': 95, 'both': 95, 'Enron': 96, '5': 97, 'always': 97, 'car': 98, 'come': 101, ';': 101, "it's": 101, "'re": 101, 'days': 102, 'What': 102, 'used': 102, 'number': 103, 'since': 103, 'price': 103, 'next': 103, '4': 104

2.f.i

In [114]:
print("Tokens Validation : ",temp_sum1)

Tokens Validation :  25478


2.f.ii word types in validation were not seen in train, Out Of Vocabulary (OOV)

In [115]:
res_set = val_type.difference(temp_sum_type)
print(res_set)
print(len(list(res_set)))

{'bellow', '3-5213', 'piss', 'Kliotech', 'lounges', 'Weblog', 'spanking', 'evacuating', 'Netscape', 'TCHO', 'fulfillment', '404-449-1026', 'Urban', 'Scotia', 'S100', 'Conservation', 'substitution', 'Valero', 'SVP', "Ray's", 'LD', 'Motorsports', 'Faz', 'Woodland', 'Alert', 'embroidery', 'Cheerleading', 'hrs', 'sheikh', '6,606', 'directors', 'smartphone', 'Shaukat', 'Omaha', 'directory', 'tradeoff', 'KS', '243,000', "o'neal", 'Fabrics', 'GG', '21202', 'goat', 'Brett', 'Pets', 'wildest', 'condemned', 'flour', 'YAY', 'billboards', 'tan', 'amenities', '12:05', 'oone', 'grammar', 'redevelopment', 'Amir', 'mi', 'propter', 'internship', 'referencing', 'SCULPTURE', 'Wo', 'Hilliard', '==----', 'PLZ', 'Mateo', 'lourdes', 'Roof', 'lols', 'matt', 'Baqubah', 'Hobbs', 'Burch', 'http://cambridgefoodfrivolity.blogspot.com/', 'Officiol', 'Synder', '3,40', 'scores', 'ENRON@enronXgate', 'annoucement', 'Miramar', 'Hancocks', 'lynx', 'ins', 'reigns', 'mated', 'modelling', 'Mannino', 'Breaking', 'Player', 'S

3.b

In [116]:
import torch
f = torch.nn.Linear(3, 2, bias=False)
f.weight = torch.nn.Parameter(
torch.Tensor([[3, 2, 1],
[1, 4, 1]]))
x = torch.Tensor([1, 0, 0])
y = f(x)
print(y)
print(f(torch.Tensor([0, 1, 0])))
print(f(torch.Tensor([0, 0, 1])))
#print(f(torch.Tensor([1, 1])))

tensor([3., 1.], grad_fn=<SqueezeBackward4>)
tensor([2., 4.], grad_fn=<SqueezeBackward4>)
tensor([1., 1.], grad_fn=<SqueezeBackward4>)


3.c

In [117]:
import torch
f = torch.nn.Linear(3, 2, bias=False)
f.weight = torch.nn.Parameter(
torch.Tensor([[3, 2, 1],
[1, 4, 1]]))
x = torch.Tensor([1, 0, 0])
y = f(x)
z=y.sum()
print(z)
z.backward()
print(z.grad)
print(f.weight.grad)
print(x.grad)

tensor(4., grad_fn=<SumBackward0>)
None
tensor([[1., 0., 0.],
        [1., 0., 0.]])
None


<ipython-input-117-e3464de4645d>:11: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:486.)
  print(z.grad)


4.b

In [118]:
import torch

x = torch.tensor(1.5)
mu = torch.tensor(5.0, requires_grad=True)

f_x = torch.exp(-1/3 * (x - mu)**3)

f_x.backward()

print(mu.grad)
print( (x - mu)**2 * torch.exp(-(1/3) * (x-mu)**3 ))

tensor(19720968.)
tensor(19720968., grad_fn=<MulBackward0>)


4.d

In [119]:
import torch

a = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)
x = torch.tensor(-2.0)

f_x = torch.log(a * (x**4) + b * (x**2) - 1)

f_x.backward()

print("df/da:",a.grad)
print("df/db:",b.grad)
print((x**4)/ (a * (x**4) + b * (x**2) - 1 ) )
print((x**2)/ (a * (x**4) + b * (x**2) - 1 ) )

df/da: tensor(0.8421)
df/db: tensor(0.2105)
tensor(0.8421, grad_fn=<DivBackward0>)
tensor(0.2105, grad_fn=<DivBackward0>)


4.g

In [120]:
import torch

#Given Matrix A of size 2x3
A=torch.tensor([[4.,2.,0.],[-1.,0.,-1.]])

#Matrix A Transpose(AT)
ATran=torch.transpose(A,0,1)
print('Matrix A:\n',A,'\nMatrix A Transpose:\n',ATran)

#A*AT & AT*A
Resultant1_Matrix=torch.matmul(A,ATran)
Resultant2_Matrix=torch.matmul(ATran,A)
print('A * AT:\n',Resultant1_Matrix,'\nAT * A:\n',Resultant2_Matrix)

Matrix A:
 tensor([[ 4.,  2.,  0.],
        [-1.,  0., -1.]]) 
Matrix A Transpose:
 tensor([[ 4., -1.],
        [ 2.,  0.],
        [ 0., -1.]])
A * AT:
 tensor([[20., -4.],
        [-4.,  2.]]) 
AT * A:
 tensor([[17.,  8.,  1.],
        [ 8.,  4.,  0.],
        [ 1.,  0.,  1.]])
